In [8]:
bata = [1,2,3,4]

In [20]:
from  prettytable import PrettyTable
import pandas as pd

In [4]:


attributes = ['name','age','team']

data = [
    ['V.Kohli','30','RCB'],
    ['chahal','28','RCB'],
    ['Sharukh','25','KKR'],
    ['chrisgayle','40','RCB'],
    ['ABd','35','RCB']
]

data = pd.DataFrame(data, columns=attributes)
data

         name age team
0     V.Kohli  30  RCB
1      chahal  28  RCB
2     Sharukh  25  KKR
3  chrisgayle  40  RCB
4         ABd  35  RCB

In [5]:
table={

'movie':['Arjun Reddy','Goat','Kalki'],
'rating':[8,9,7],
'hero':['Vijay','R','Prabhas']

}

for key in table:
    print(f"{key}:{table[key]}")

movie:['Arjun Reddy', 'Goat', 'Kalki']
rating:[8, 9, 7]
hero:['Vijay', 'R', 'Prabhas']

In [22]:


table = PrettyTable(['movie','rating','hero'])
table.add_row(['Arjun Reddy',8,'Vijay'])
table.add_row(['Goat',9,'R'])
table.add_row(['Kalki',7,'Prabhas'])
table.add_row(['KGF',8,'Yash'])
print(table)

+-------------+--------+---------+
|    movie    | rating |   hero  |
+-------------+--------+---------+
| Arjun Reddy |   8    |  Vijay  |
|     Goat    |   9    |    R    |
|    Kalki    |   7    | Prabhas |
|     KGF     |   8    |   Yash  |
+-------------+--------+---------+

In [25]:
data= pd.read_csv('/Users/surisettivamsikrishna/Downloads/Vamsi Pc/CODES/Mark 3/Cleaned_Data/Monthly_Trades.csv')
data.head()

           MONTH   NO OF TRADES REALIZED PL   CHARGES NET REALIZED\nPL
0    January-2025             8   -₹ 126.37  ₹ 239.70        -₹ 366.07
1   November-2024             5   -₹ 947.90  ₹ 119.17      -₹ 1,067.07
2    October-2024            14    ₹ 341.05  ₹ 596.97        -₹ 255.92
3  September-2024             2   -₹ 469.45  ₹ 110.01        -₹ 579.46
4     August-2024            11   -₹ 151.10  ₹ 237.74        -₹ 388.84

#### Cleaning unwanted cells

In [26]:
fata=pd.read_csv('/Users/surisettivamsikrishna/Downloads/Vamsi Pc/CODES/Mark 3/Cleaned_Data/Monthly_Trades.csv')
fata.head()

           MONTH   NO OF TRADES REALIZED PL   CHARGES NET REALIZED\nPL
0    January-2025             8   -₹ 126.37  ₹ 239.70        -₹ 366.07
1   November-2024             5   -₹ 947.90  ₹ 119.17      -₹ 1,067.07
2    October-2024            14    ₹ 341.05  ₹ 596.97        -₹ 255.92
3  September-2024             2   -₹ 469.45  ₹ 110.01        -₹ 579.46
4     August-2024            11   -₹ 151.10  ₹ 237.74        -₹ 388.84