## Understanding Universal Stats

Explicitly when I trade, consisder these Factors to be important.
Finding Co-relations between them and adding conditional probability, with matching a strategy would help me get a good strategy!

Aiming for atleast 70% accuracy !!

In [16]:
import pandas as pd
FDI = pd.read_csv("/Users/surisettivamsikrishna/Downloads/Vamsi Pc/CODES/Mark 3/UNIV DATA/FII:DII.csv")

FDI.head(5)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,FII,NaN,NaN,DII,NaN,NaN
3,NaN,Date,Gross Purchase,Gross Sales,Net Purchase / Sales,Gross Purchase,Gross Sales,Net Purchase / Sales
4,NaN,Total,259256.89,318244.97,-58988.08,277187,212333.81,64853.19

In [17]:
FDI= FDI.iloc[3:,1:]
FDI.head(5)

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
3,Date,Gross Purchase,Gross Sales,Net Purchase / Sales,Gross Purchase,Gross Sales,Net Purchase / Sales
4,Total,259256.89,318244.97,-58988.08,277187,212333.81,64853.19
5,28-Feb-2025,"39,239.44","50,878.46","-11,639.02","28,065.55","15,756.92","12,308.63"
6,27-Feb-2025,"19,055.23","19,611.79",-556.56,"13,530.17","11,803.06","1,727.11"
7,25-Feb-2025,"12,500.37","16,029.47","-3,529.10","11,278.09","8,247.31","3,030.78"

In [18]:
FDI.reset_index(drop=True)
FDI.columns=FDI.iloc[0]
FDI=FDI.iloc[1:].reset_index(drop=True)

In [21]:
FDI=FDI.iloc[1:]
FDI.head(5)

3,Date,Gross Purchase,Gross Sales,Net Purchase / Sales,Gross Purchase,Gross Sales,Net Purchase / Sales
1,28-Feb-2025,"39,239.44","50,878.46","-11,639.02","28,065.55","15,756.92","12,308.63"
2,27-Feb-2025,"19,055.23","19,611.79",-556.56,"13,530.17","11,803.06","1,727.11"
3,25-Feb-2025,"12,500.37","16,029.47","-3,529.10","11,278.09","8,247.31","3,030.78"
4,24-Feb-2025,"7,905.53","14,192.23","-6,286.70","12,552.14","7,366.49","5,185.65"
5,21-Feb-2025,"10,144.33","13,593.48","-3,449.15","12,889.44","10,004.83","2,884.61"

In [23]:
FDI.columns = ['Date', 'Gross Purchase FII', 'Gross Sales FII', 'Net Purchase FII',
               'Gross Purchase DII', 'Gross Sales DII', 'Net Purchase DII']
FDI.head(5)

,Date,Gross Purchase FII,Gross Sales FII,Net Purchase FII,Gross Purchase DII,Gross Sales DII,Net Purchase DII
1,28-Feb-2025,"39,239.44","50,878.46","-11,639.02","28,065.55","15,756.92","12,308.63"
2,27-Feb-2025,"19,055.23","19,611.79",-556.56,"13,530.17","11,803.06","1,727.11"
3,25-Feb-2025,"12,500.37","16,029.47","-3,529.10","11,278.09","8,247.31","3,030.78"
4,24-Feb-2025,"7,905.53","14,192.23","-6,286.70","12,552.14","7,366.49","5,185.65"
5,21-Feb-2025,"10,144.33","13,593.48","-3,449.15","12,889.44","10,004.83","2,884.61"

In [24]:
FDI.to_csv("/Users/surisettivamsikrishna/Downloads/Vamsi Pc/CODES/Mark 3/Cleaned_Data_UD/FDI.csv")

In [46]:
GOLD=pd.read_csv("/Users/surisettivamsikrishna/Downloads/Vamsi Pc/CODES/Mark 3/UNIV DATA/GOLD - Sheet1.csv")
GOLD.head(5)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Date,Price,Open,High,Low,Vol.,Change %
2,NaN,"Mar 03, 2025","2,882.61","2,882.06","2,888.59","2,868.90",82.35K,0.00%
3,NaN,"Mar 02, 2025","2,882.47","2,867.85","2,888.15","2,867.40",0.01K,0.0119
4,NaN,"Feb 28, 2025","2,848.50","2,889.00","2,896.10","2,844.10",210.56K,-1.64%

In [48]:
GOLD1=GOLD.iloc[1:,1:]
GOLD1.head(5)

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
1,Date,Price,Open,High,Low,Vol.,Change %
2,"Mar 03, 2025","2,882.61","2,882.06","2,888.59","2,868.90",82.35K,0.00%
3,"Mar 02, 2025","2,882.47","2,867.85","2,888.15","2,867.40",0.01K,0.0119
4,"Feb 28, 2025","2,848.50","2,889.00","2,896.10","2,844.10",210.56K,-1.64%
5,"Feb 27, 2025","2,895.90","2,931.40","2,935.80","2,879.00",207.65K,-0.75%

In [58]:
GOLD1.columns=GOLD1.iloc[0]
GOLD1.reset_index(drop=True)
GOLD1.head(5)

1          Date     Price      Open      High       Low     Vol.  Change %
1          Date     Price      Open      High       Low     Vol.  Change %
2  Mar 03, 2025  2,882.61  2,882.06  2,888.59  2,868.90   82.35K     0.00%
3  Mar 02, 2025  2,882.47  2,867.85  2,888.15  2,867.40    0.01K    0.0119
4  Feb 28, 2025  2,848.50  2,889.00  2,896.10  2,844.10  210.56K    -1.64%
5  Feb 27, 2025  2,895.90  2,931.40  2,935.80  2,879.00  207.65K    -0.75%

In [72]:
GOLD2=GOLD1.iloc[1:]
GOLD2.head(5)

1          Date     Price      Open      High       Low     Vol. Change %
2  Mar 03, 2025  2,882.61  2,882.06  2,888.59  2,868.90   82.35K    0.00%
3  Mar 02, 2025  2,882.47  2,867.85  2,888.15  2,867.40    0.01K   0.0119
4  Feb 28, 2025  2,848.50  2,889.00  2,896.10  2,844.10  210.56K   -1.64%
5  Feb 27, 2025  2,895.90  2,931.40  2,935.80  2,879.00  207.65K   -0.75%
6  Feb 26, 2025  2,917.80  2,915.60  2,926.40  2,891.00    2.05K   0.0041

In [82]:
GOLD2['Yesterday Price']=GOLD2['Price'].shift(-1)
GOLD2.head(5)

/var/folders/10/4p6gdwfx3g74kjfj2_xqxz140000gn/T/ipykernel_1209/2623556838.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GOLD2['Yesterday Price']=GOLD2['Price'].shift(-1)

1,Date,Price,Open,High,Low,Vol.,Change %,Yesterday Price
2,"Mar 03, 2025","2,882.61","2,882.06","2,888.59","2,868.90",82.35K,0.00%,"2,882.47"
3,"Mar 02, 2025","2,882.47","2,867.85","2,888.15","2,867.40",0.01K,0.0119,"2,848.50"
4,"Feb 28, 2025","2,848.50","2,889.00","2,896.10","2,844.10",210.56K,-1.64%,"2,895.90"
5,"Feb 27, 2025","2,895.90","2,931.40","2,935.80","2,879.00",207.65K,-0.75%,"2,917.80"
6,"Feb 26, 2025","2,917.80","2,915.60","2,926.40","2,891.00",2.05K,0.0041,"2,906.00"

In [83]:
GOLD3=GOLD2.iloc[1:]
GOLD3.head(5)

1,Date,Price,Open,High,Low,Vol.,Change %,Yesterday Price
3,"Mar 02, 2025","2,882.47","2,867.85","2,888.15","2,867.40",0.01K,0.0119,"2,848.50"
4,"Feb 28, 2025","2,848.50","2,889.00","2,896.10","2,844.10",210.56K,-1.64%,"2,895.90"
5,"Feb 27, 2025","2,895.90","2,931.40","2,935.80","2,879.00",207.65K,-0.75%,"2,917.80"
6,"Feb 26, 2025","2,917.80","2,915.60","2,926.40","2,891.00",2.05K,0.0041,"2,906.00"
7,"Feb 25, 2025","2,906.00","2,955.90","2,955.90","2,884.50",5.59K,-1.48%,"2,949.70"

In [84]:
GOLD3.dtypes

1
Date               object
Price              object
Open               object
High               object
Low                object
Vol.               object
Change %           object
Yesterday Price    object
dtype: object

In [85]:
GOLD3['Price'] = GOLD3['Price'].str.replace(',', '', regex=True).astype(float)
GOLD3['Yesterday Price'] = GOLD3['Yesterday Price'].str.replace(',', '', regex=True).astype(float)

GOLD3['Change Pts'] = GOLD3['Price'] - GOLD3['Yesterday Price']

/var/folders/10/4p6gdwfx3g74kjfj2_xqxz140000gn/T/ipykernel_1209/3198500820.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GOLD3['Price'] = GOLD3['Price'].str.replace(',', '', regex=True).astype(float)
/var/folders/10/4p6gdwfx3g74kjfj2_xqxz140000gn/T/ipykernel_1209/3198500820.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GOLD3['Yesterday Price'] = GOLD3['Yesterday Price'].str.replace(',', '', regex=True).astype(float)
/var/folders/10/4p6gdwfx3g74kjfj2_xqxz140000gn/T/ipykernel_1209/3198500820.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GOLD3['Change Pts'] = GOLD3['Price'] - GOLD3['Yesterday Price']

In [86]:
GOLD3['Change Pts']=GOLD3['Price']-GOLD3['Yesterday Price']
GOLD3.head(5)

/var/folders/10/4p6gdwfx3g74kjfj2_xqxz140000gn/T/ipykernel_1209/2937414243.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GOLD3['Change Pts']=GOLD3['Price']-GOLD3['Yesterday Price']

1,Date,Price,Open,High,Low,Vol.,Change %,Yesterday Price,Change Pts
3,"Mar 02, 2025",2882.47,"2,867.85","2,888.15","2,867.40",0.01K,0.0119,2848.5,33.97
4,"Feb 28, 2025",2848.50,"2,889.00","2,896.10","2,844.10",210.56K,-1.64%,2895.9,-47.40
5,"Feb 27, 2025",2895.90,"2,931.40","2,935.80","2,879.00",207.65K,-0.75%,2917.8,-21.90
6,"Feb 26, 2025",2917.80,"2,915.60","2,926.40","2,891.00",2.05K,0.0041,2906.0,11.80
7,"Feb 25, 2025",2906.00,"2,955.90","2,955.90","2,884.50",5.59K,-1.48%,2949.7,-43.70

In [92]:
GOLD3['Change Pts'].iloc[-1:]

107   NaN
Name: Change Pts, dtype: float64

In [93]:
GOLD4=GOLD3.iloc[:-1]
GOLD4.head(5)

1,Date,Price,Open,High,Low,Vol.,Change %,Yesterday Price,Change Pts
3,"Mar 02, 2025",2882.47,"2,867.85","2,888.15","2,867.40",0.01K,0.0119,2848.5,33.97
4,"Feb 28, 2025",2848.50,"2,889.00","2,896.10","2,844.10",210.56K,-1.64%,2895.9,-47.40
5,"Feb 27, 2025",2895.90,"2,931.40","2,935.80","2,879.00",207.65K,-0.75%,2917.8,-21.90
6,"Feb 26, 2025",2917.80,"2,915.60","2,926.40","2,891.00",2.05K,0.0041,2906.0,11.80
7,"Feb 25, 2025",2906.00,"2,955.90","2,955.90","2,884.50",5.59K,-1.48%,2949.7,-43.70

In [95]:
GOLD4.shape

(104, 9)

In [96]:
GOLD4.to_csv("/Users/surisettivamsikrishna/Downloads/Vamsi Pc/CODES/Mark 3/Cleaned_Data_UD/GOLD.csv")