In [249]:
import pandas as pd
import numpy as np

In [250]:
od= pd.read_csv("/Users/surisettivamsikrishna/Downloads/Vamsi Pc/CODES/Mark 3/Raw_Data/official_data.csv")
od.head(5)

,Date Range,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,From Date,31/07/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,To Date,20/01/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Equity P&L Summary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Total Gross PnL,-1353.77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [251]:
od.iloc[25]
od.shape

(67, 20)

In [252]:
od.iloc[25]

Date Range             Scrip Symbol
Unnamed: 1             Company Name
Unnamed: 2                 Quantity
Unnamed: 3            Avg Buy Price
Unnamed: 4                Buy Value
Unnamed: 5           Avg Sell Price
Unnamed: 6               Sell Value
Unnamed: 7                Gross PnL
Unnamed: 8                Brokerage
Unnamed: 9                      GST
Unnamed: 10    Exchange Service Tax
Unnamed: 11            Turnover Tax
Unnamed: 12            SEBI Charges
Unnamed: 13              Stamp Duty
Unnamed: 14                     STT
Unnamed: 15           Other Charges
Unnamed: 16            IPFT Charges
Unnamed: 17            Intraday PnL
Unnamed: 18                     NaN
Unnamed: 19                     NaN
Name: 25, dtype: object

In [254]:
od1 = od.iloc[25:67]
od1.head(5)

,Date Range,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
25,Scrip Symbol,Company Name,Quantity,Avg Buy Price,Buy Value,Avg Sell Price,Sell Value,Gross PnL,Brokerage,GST,Exchange Service Tax,Turnover Tax,SEBI Charges,Stamp Duty,STT,Other Charges,IPFT Charges,Intraday PnL,NaN,NaN
26,LT,LARSEN & TOUBRO LTD.,20,3590.63,71812.5,3587.98,71759.5,-53,43.07,8.57,0,4.26,0.14,2,18,0,0.14,-129.19,NaN,NaN
27,RELIANCE,RELIANCE INDUSTRIES LTD,20,1243.65,24873,1239.1,24782,-91,14.9,2.96,0,1.47,0.05,1,6,0,0.05,-117.44,NaN,NaN
28,TCS,TATA CONSULTANCY SERV LT,6,4301.5,25809,4273.55,25641.3,-167.7,15.44,3.07,0,1.53,0.05,1,6,0,0.05,-194.84,NaN,NaN
29,IREDA,INDIAN RENEWABLE ENERGY,60,215.4,12924,212.11,12726.53,-197.47,7.7,1.53,0,0.76,0.03,0,3,0,0.03,-210.51,NaN,NaN

In [256]:
od1.columns = od1.iloc[0]
od1 = od1.drop(od1.index[0])
od1.head(5)

25,Scrip Symbol,Company Name,Quantity,Avg Buy Price,Buy Value,Avg Sell Price,Sell Value,Gross PnL,Brokerage,GST,Exchange Service Tax,Turnover Tax,SEBI Charges,Stamp Duty,STT,Other Charges,IPFT Charges,Intraday PnL,NaN,NaN
26,LT,LARSEN & TOUBRO LTD.,20,3590.63,71812.5,3587.98,71759.5,-53,43.07,8.57,0,4.26,0.14,2,18,0,0.14,-129.19,NaN,NaN
27,RELIANCE,RELIANCE INDUSTRIES LTD,20,1243.65,24873,1239.1,24782,-91,14.9,2.96,0,1.47,0.05,1,6,0,0.05,-117.44,NaN,NaN
28,TCS,TATA CONSULTANCY SERV LT,6,4301.5,25809,4273.55,25641.3,-167.7,15.44,3.07,0,1.53,0.05,1,6,0,0.05,-194.84,NaN,NaN
29,IREDA,INDIAN RENEWABLE ENERGY,60,215.4,12924,212.11,12726.53,-197.47,7.7,1.53,0,0.76,0.03,0,3,0,0.03,-210.51,NaN,NaN
30,M&M,MAHINDRA & MAHINDRA LTD,9,3133.96,28205.65,3122.1,28098.9,-106.75,16.89,3.36,0,1.67,0.06,1,7,0,0.06,-136.79,NaN,NaN

In [257]:
od1.columns

Index([        'Scrip Symbol',         'Company Name',             'Quantity',
              'Avg Buy Price',            'Buy Value',       'Avg Sell Price',
                 'Sell Value',            'Gross PnL',            'Brokerage',
                        'GST', 'Exchange Service Tax',         'Turnover Tax',
               'SEBI Charges',           'Stamp Duty',                  'STT',
              'Other Charges',         'IPFT Charges',         'Intraday PnL',
                          nan,                    nan],
      dtype='object', name=25)

In [258]:
columns_added = ['GST', 'Exchange Service Tax',         'Turnover Tax',
               'SEBI Charges',           'Stamp Duty',                  'STT',
              'Other Charges',         'IPFT Charges']

In [259]:
od1['Add Charges'] = od1[columns_added].sum(axis=1)
od1 = od1.drop(columns=columns_added)
od1 = od1.drop(columns=[col for col in od1.columns if pd.isna(col)])

od1.head(5)

25,Scrip Symbol,Company Name,Quantity,Avg Buy Price,Buy Value,Avg Sell Price,Sell Value,Gross PnL,Brokerage,Intraday PnL,Add Charges
26,LT,LARSEN & TOUBRO LTD.,20,3590.63,71812.5,3587.98,71759.5,-53,43.07,-129.19,8.5704.260.1421800.14
27,RELIANCE,RELIANCE INDUSTRIES LTD,20,1243.65,24873,1239.1,24782,-91,14.9,-117.44,2.9601.470.051600.05
28,TCS,TATA CONSULTANCY SERV LT,6,4301.5,25809,4273.55,25641.3,-167.7,15.44,-194.84,3.0701.530.051600.05
29,IREDA,INDIAN RENEWABLE ENERGY,60,215.4,12924,212.11,12726.53,-197.47,7.7,-210.51,1.5300.760.030300.03
30,M&M,MAHINDRA & MAHINDRA LTD,9,3133.96,28205.65,3122.1,28098.9,-106.75,16.89,-136.79,3.3601.670.061700.06

In [215]:
od1 = od1.drop(columns=[col for col in od1.columns if pd.isna(col)])
od1.head()

25,Scrip Symbol,Company Name,Quantity,Avg Buy Price,Buy Value,Avg Sell Price,Sell Value,Gross PnL,Brokerage,Intraday PnL,Add Charges
0,LT,LARSEN & TOUBRO LTD.,20,3590.63,71812.5,3587.98,71759.5,-53,43.07,-129.19,8.5704.260.1421800.14
1,RELIANCE,RELIANCE INDUSTRIES LTD,20,1243.65,24873,1239.1,24782,-91,14.9,-117.44,2.9601.470.051600.05
2,TCS,TATA CONSULTANCY SERV LT,6,4301.5,25809,4273.55,25641.3,-167.7,15.44,-194.84,3.0701.530.051600.05
3,IREDA,INDIAN RENEWABLE ENERGY,60,215.4,12924,212.11,12726.53,-197.47,7.7,-210.51,1.5300.760.030300.03
4,M&M,MAHINDRA & MAHINDRA LTD,9,3133.96,28205.65,3122.1,28098.9,-106.75,16.89,-136.79,3.3601.670.061700.06

In [216]:
col_order= od1.columns.tolist()
col_order.insert(col_order.index("Brokerage")+1,col_order.pop(col_order.index("Add Charges")))
od1=od1[col_order]
od1.head()

25,Scrip Symbol,Company Name,Quantity,Avg Buy Price,Buy Value,Avg Sell Price,Sell Value,Gross PnL,Brokerage,Add Charges,Intraday PnL
0,LT,LARSEN & TOUBRO LTD.,20,3590.63,71812.5,3587.98,71759.5,-53,43.07,8.5704.260.1421800.14,-129.19
1,RELIANCE,RELIANCE INDUSTRIES LTD,20,1243.65,24873,1239.1,24782,-91,14.9,2.9601.470.051600.05,-117.44
2,TCS,TATA CONSULTANCY SERV LT,6,4301.5,25809,4273.55,25641.3,-167.7,15.44,3.0701.530.051600.05,-194.84
3,IREDA,INDIAN RENEWABLE ENERGY,60,215.4,12924,212.11,12726.53,-197.47,7.7,1.5300.760.030300.03,-210.51
4,M&M,MAHINDRA & MAHINDRA LTD,9,3133.96,28205.65,3122.1,28098.9,-106.75,16.89,3.3601.670.061700.06,-136.79

In [260]:
od1["Opted"]=np.where(od1["Avg Buy Price"]<od1["Avg Sell Price"],"BUYYY","SELL")
od1.tail(5)

25,Scrip Symbol,Company Name,Quantity,Avg Buy Price,Buy Value,Avg Sell Price,Sell Value,Gross PnL,Brokerage,Intraday PnL,Add Charges,Opted
62,TATAMOTORS,TATA MOTORS LIMITED,17,1079,18343,1073.8,18254.6,-88.4,10.98,-108.79,2.1901.180.041500,SELL
63,TATAMOTORS,TATA MOTORS LIMITED,19,1049.25,19935.75,1040.35,19766.65,-169.1,11.91,-190.71,2.3801.280.041500,SELL
64,TATAMOTORS,TATA MOTORS LIMITED,20,1026.75,20535,1020.46,20409.1,-125.9,12.28,-148,2.4601.320.041500,SELL
65,TATAMOTORS,TATA MOTORS LIMITED,18,1045.8,18824.4,1057.55,19035.9,211.5,11.36,190.61,2.2701.220.041500,BUYYY
66,Total,NaN,NaN,NaN,1224006.1,NaN,1222652.33,-1353.77,733.99,-2657.35,146.35075.062.4741302.9901.72,SELL

In [267]:
od1 = od1[::-1].reset_index(drop=True)

od1.head(5)

25,Scrip Symbol,Company Name,Quantity,Avg Buy Price,Buy Value,Avg Sell Price,Sell Value,Gross PnL,Brokerage,Intraday PnL,Add Charges,Opted
0,Total,NaN,NaN,NaN,1224006.1,NaN,1222652.33,-1353.77,733.99,-2657.35,146.35075.062.4741302.9901.72,SELL
1,TATAMOTORS,TATA MOTORS LIMITED,18,1045.8,18824.4,1057.55,19035.9,211.5,11.36,190.61,2.2701.220.041500,BUYYY
2,TATAMOTORS,TATA MOTORS LIMITED,20,1026.75,20535,1020.46,20409.1,-125.9,12.28,-148,2.4601.320.041500,SELL
3,TATAMOTORS,TATA MOTORS LIMITED,19,1049.25,19935.75,1040.35,19766.65,-169.1,11.91,-190.71,2.3801.280.041500,SELL
4,TATAMOTORS,TATA MOTORS LIMITED,17,1079,18343,1073.8,18254.6,-88.4,10.98,-108.79,2.1901.180.041500,SELL

In [268]:
od1=od1.iloc[1:]
od1.head(5)

25,Scrip Symbol,Company Name,Quantity,Avg Buy Price,Buy Value,Avg Sell Price,Sell Value,Gross PnL,Brokerage,Intraday PnL,Add Charges,Opted
1,TATAMOTORS,TATA MOTORS LIMITED,18,1045.8,18824.4,1057.55,19035.9,211.5,11.36,190.61,2.2701.220.041500,BUYYY
2,TATAMOTORS,TATA MOTORS LIMITED,20,1026.75,20535,1020.46,20409.1,-125.9,12.28,-148,2.4601.320.041500,SELL
3,TATAMOTORS,TATA MOTORS LIMITED,19,1049.25,19935.75,1040.35,19766.65,-169.1,11.91,-190.71,2.3801.280.041500,SELL
4,TATAMOTORS,TATA MOTORS LIMITED,17,1079,18343,1073.8,18254.6,-88.4,10.98,-108.79,2.1901.180.041500,SELL
5,TATAMOTORS,TATA MOTORS LIMITED,34,1059.88,36035.75,1063.29,36152,116.25,21.66,77.86,4.3302.320.071900,BUYYY

In [220]:
od1 = pd.concat([od1.iloc[1:], od1.iloc[[0]]]).reset_index(drop=True)

In [269]:
od1.head(5)

25,Scrip Symbol,Company Name,Quantity,Avg Buy Price,Buy Value,Avg Sell Price,Sell Value,Gross PnL,Brokerage,Intraday PnL,Add Charges,Opted
1,TATAMOTORS,TATA MOTORS LIMITED,18,1045.8,18824.4,1057.55,19035.9,211.5,11.36,190.61,2.2701.220.041500,BUYYY
2,TATAMOTORS,TATA MOTORS LIMITED,20,1026.75,20535,1020.46,20409.1,-125.9,12.28,-148,2.4601.320.041500,SELL
3,TATAMOTORS,TATA MOTORS LIMITED,19,1049.25,19935.75,1040.35,19766.65,-169.1,11.91,-190.71,2.3801.280.041500,SELL
4,TATAMOTORS,TATA MOTORS LIMITED,17,1079,18343,1073.8,18254.6,-88.4,10.98,-108.79,2.1901.180.041500,SELL
5,TATAMOTORS,TATA MOTORS LIMITED,34,1059.88,36035.75,1063.29,36152,116.25,21.66,77.86,4.3302.320.071900,BUYYY

In [270]:
uod=pd.read_csv("/Users/surisettivamsikrishna/Downloads/Vamsi Pc/CODES/Mark 3/Raw_Data/Unofficial_data1.csv")
uod.head()

,Pre Funds,DATE,STOCK,OPTED,VOLUME,RSI,RR,TAR RR,PR0 / LOSS,Brokerage,NET,Post Funds
0,4000.00,August 5,TATA Motors,BUY,1.4M u - 450k,30,2,2.0,210.00,NaN,190.69,4190.00
1,4190.00,August 7,TATA Motors,No Data,NO DATA AVAILABLE,NaN,NaN,NaN,126.00,NaN,-148.00,4042.00
2,4042.00,August 8,TATA Motors,NaN,NaN,NaN,NaN,NaN,169.00,NaN,-190.71,3851.00
3,3851.00,August 12,TATA Motors,NaN,NaN,NaN,NaN,NaN,88.00,NaN,-108.79,3742.21
4,3742.21,August 13,TATA Motors,NaN,NaN,NaN,NaN,NaN,115.94,NaN,77.44,3819.65

In [272]:
od1.head(5)

25,Scrip Symbol,Company Name,Quantity,Avg Buy Price,Buy Value,Avg Sell Price,Sell Value,Gross PnL,Brokerage,Intraday PnL,Add Charges,Opted
1,TATAMOTORS,TATA MOTORS LIMITED,18,1045.8,18824.4,1057.55,19035.9,211.5,11.36,190.61,2.2701.220.041500,BUYYY
2,TATAMOTORS,TATA MOTORS LIMITED,20,1026.75,20535,1020.46,20409.1,-125.9,12.28,-148,2.4601.320.041500,SELL
3,TATAMOTORS,TATA MOTORS LIMITED,19,1049.25,19935.75,1040.35,19766.65,-169.1,11.91,-190.71,2.3801.280.041500,SELL
4,TATAMOTORS,TATA MOTORS LIMITED,17,1079,18343,1073.8,18254.6,-88.4,10.98,-108.79,2.1901.180.041500,SELL
5,TATAMOTORS,TATA MOTORS LIMITED,34,1059.88,36035.75,1063.29,36152,116.25,21.66,77.86,4.3302.320.071900,BUYYY

In [275]:
mod1=od1.to_csv('/Users/surisettivamsikrishna/Downloads/Vamsi Pc/CODES/Mark 3/Cleaned_Data/MOD2.csv')

In [278]:
mod2=pd.read_csv('/Users/surisettivamsikrishna/Downloads/Vamsi Pc/CODES/Mark 3/Cleaned_Data/MOD2.csv')
mod2.head()

,Unnamed: 0,Scrip Symbol,Company Name,Quantity,Avg Buy Price,Buy Value,Avg Sell Price,Sell Value,Gross PnL,Brokerage,Intraday PnL,Add Charges,Opted
0,1,TATAMOTORS,TATA MOTORS LIMITED,18,1045.80,18824.40,1057.55,19035.90,211.50,11.36,190.61,2.2701.220.041500,BUYYY
1,2,TATAMOTORS,TATA MOTORS LIMITED,20,1026.75,20535.00,1020.46,20409.10,-125.90,12.28,-148.00,2.4601.320.041500,SELL
2,3,TATAMOTORS,TATA MOTORS LIMITED,19,1049.25,19935.75,1040.35,19766.65,-169.10,11.91,-190.71,2.3801.280.041500,SELL
3,4,TATAMOTORS,TATA MOTORS LIMITED,17,1079.00,18343.00,1073.80,18254.60,-88.40,10.98,-108.79,2.1901.180.041500,SELL
4,5,TATAMOTORS,TATA MOTORS LIMITED,34,1059.88,36035.75,1063.29,36152.00,116.25,21.66,77.86,4.3302.320.071900,BUYYY

In [279]:
comparsion=pd.DataFrame({'od1':mod2['Scrip Symbol'],'od2':uod['STOCK']})
print(comparsion)

           od1              od2
0   TATAMOTORS      TATA Motors
1   TATAMOTORS      TATA Motors
2   TATAMOTORS      TATA Motors
3   TATAMOTORS      TATA Motors
4   TATAMOTORS      TATA Motors
5   TATAMOTORS      TATA Motors
6   TATAMOTORS      TATA Motors
7   TATAMOTORS      TATA Motors
8   TATAMOTORS      TATA Motors
9   TATAMOTORS      TATA Motors
10  TATAMOTORS      TATA Motors
11        OFSS             OFSS
12        OFSS             OFSS
13     OLAELEC          OLAELEC
14         TCS              TCS
15    ADANIENT        Adani Ent
16          LT               LT
17      APOLLO        Apollo MS
18   SOUTHBANK  South INdian Bk
19     MAZDOCK          MAZDOCK
20        INFY             Infy
21          LT               LT
22    HDFCLIFE        Hdfc Life
23  TATAMOTORS      Tata Motors
24    RELIANCE         Reliance
25       TECHM           Tech M
26       WIPRO            Wipro
27   TATASTEEL      tata steel
28  TATAMOTORS      tata steel
29       ABFRL       AB Fashion
30        NTPC             NTPC
31  TATAMOTORS      Tata Motors
32          LT               LT
33       TITAN            Titan
34       TRENT            TRENT
35         M&M              M&M
36       IREDA            IREDA
37         TCS              TCS
38         NaN         Reliance
39         NaN               LT

In [224]:
od1.to_csv("/Users/surisettivamsikrishna/Downloads/Vamsi Pc/CODES/Mark 3/Raw_Data/MOD1.csv",index=False)

In [280]:
od2=pd.read_csv("/Users/surisettivamsikrishna/Downloads/Vamsi Pc/CODES/Mark 3/Cleaned_Data/MOD1.csv")
od2.head()

,Scrip Symbol,Company Name,Quantity,Avg Buy Price,Buy Value,Avg Sell Price,Sell Value,Gross PnL,Brokerage,Add Charges,Intraday PnL,Opted
0,TATAMOTORS,TATA MOTORS LIMITED,18.0,1045.80,18824.40,1057.55,19035.90,211.50,11.36,2.2701.220.041500,190.61,BUYYY
1,TATAMOTORS,TATA MOTORS LIMITED,20.0,1026.75,20535.00,1020.46,20409.10,-125.90,12.28,2.4601.320.041500,-148.00,SELL
2,TATAMOTORS,TATA MOTORS LIMITED,19.0,1049.25,19935.75,1040.35,19766.65,-169.10,11.91,2.3801.280.041500,-190.71,SELL
3,TATAMOTORS,TATA MOTORS LIMITED,17.0,1079.00,18343.00,1073.80,18254.60,-88.40,10.98,2.1901.180.041500,-108.79,SELL
4,TATAMOTORS,TATA MOTORS LIMITED,34.0,1059.88,36035.75,1063.29,36152.00,116.25,21.66,4.3302.320.071900,77.86,BUYYY

In [281]:
col_to_move=['Pre Funds ','DATE','VOLUME','RSI','RR','TAR RR','Post Funds ']
od2=pd.concat([od2,uod[col_to_move]],axis=1)
od2.head(5)

,Scrip Symbol,Company Name,Quantity,Avg Buy Price,Buy Value,Avg Sell Price,Sell Value,Gross PnL,Brokerage,Add Charges,Intraday PnL,Opted,Pre Funds,DATE,VOLUME,RSI,RR,TAR RR,Post Funds
0,TATAMOTORS,TATA MOTORS LIMITED,18.0,1045.80,18824.40,1057.55,19035.90,211.50,11.36,2.2701.220.041500,190.61,BUYYY,4000.00,August 5,1.4M u - 450k,30,2,2.0,4190.00
1,TATAMOTORS,TATA MOTORS LIMITED,20.0,1026.75,20535.00,1020.46,20409.10,-125.90,12.28,2.4601.320.041500,-148.00,SELL,4190.00,August 7,NO DATA AVAILABLE,NaN,NaN,NaN,4042.00
2,TATAMOTORS,TATA MOTORS LIMITED,19.0,1049.25,19935.75,1040.35,19766.65,-169.10,11.91,2.3801.280.041500,-190.71,SELL,4042.00,August 8,NaN,NaN,NaN,NaN,3851.00
3,TATAMOTORS,TATA MOTORS LIMITED,17.0,1079.00,18343.00,1073.80,18254.60,-88.40,10.98,2.1901.180.041500,-108.79,SELL,3851.00,August 12,NaN,NaN,NaN,NaN,3742.21
4,TATAMOTORS,TATA MOTORS LIMITED,34.0,1059.88,36035.75,1063.29,36152.00,116.25,21.66,4.3302.320.071900,77.86,BUYYY,3742.21,August 13,NaN,NaN,NaN,NaN,3819.65

In [282]:
cols = list(od2.columns)

In [235]:
od1 = od1[::-1].reset_index(drop=True)
od1.head(5)

,Scrip Symbol,Company Name,Quantity,Avg Buy Price,Buy Value,Avg Sell Price,Sell Value,Gross PnL,Brokerage,Add Charges,Intraday PnL,Opted,Pre Funds,DATE,VOLUME,RSI,RR,TAR RR,Post Funds
0,LT,LARSEN & TOUBRO LTD.,20,3590.63,71812.5,3587.98,71759.5,-53,43.07,8.5704.260.1421800.14,-129.19,SELL,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Total,NaN,NaN,NaN,1224006.1,NaN,1222652.33,-1353.77,733.99,146.35075.062.4741302.9901.72,-2657.35,SELL,7427.48,20 Jan,39K ↑ - 26k,77,Lx2,3.0,7298.28
2,TATAMOTORS,TATA MOTORS LIMITED,18,1045.8,18824.4,1057.55,19035.9,211.5,11.36,2.2701.220.041500,190.61,BUYYY,7492.04,14 Jan,NaN,NaN,L,2.0,7427.48
3,TATAMOTORS,TATA MOTORS LIMITED,20,1026.75,20535,1020.46,20409.1,-125.9,12.28,2.4601.320.041500,-148,SELL,7632.60,13 Jan,NO,NaN,L,2.0,7492.04
4,TATAMOTORS,TATA MOTORS LIMITED,19,1049.25,19935.75,1040.35,19766.65,-169.1,11.91,2.3801.280.041500,-190.71,SELL,7843.11,10 Jan,4M-1.7M,28,L,2.0,7632.60

In [229]:
od1.to_csv("/Users/surisettivamsikrishna/Downloads/Vamsi Pc/CODES/Mark 3/Cleaned_Data/MOD2.csv")

### Second part of DATA MODIFICATION

Plan is to,
1. Fill in empty values
2. Add extra Data (
    US Bond yields,
    Indian Market Changes,
    FII/DII Data,
    Gold Rates,
    Extra Variable Data eg. Gift
)

In [290]:
uod.head(5)

,Pre Funds,DATE,STOCK,OPTED,VOLUME,RSI,RR,TAR RR,PR0 / LOSS,Brokerage,NET,Post Funds
0,4000.00,August 5,TATA Motors,BUY,1.4M u - 450k,30,2,2.0,210.00,NaN,190.69,4190.00
1,4190.00,August 7,TATA Motors,No Data,NO DATA AVAILABLE,NaN,NaN,NaN,126.00,NaN,-148.00,4042.00
2,4042.00,August 8,TATA Motors,NaN,NaN,NaN,NaN,NaN,169.00,NaN,-190.71,3851.00
3,3851.00,August 12,TATA Motors,NaN,NaN,NaN,NaN,NaN,88.00,NaN,-108.79,3742.21
4,3742.21,August 13,TATA Motors,NaN,NaN,NaN,NaN,NaN,115.94,NaN,77.44,3819.65

In [291]:
col_add = [
    'Pre Funds ',
    'Post Funds ',
    'DATE',
    'RSI',
    'VOLUME',
    'RR',
    'TAR RR'
]
pd.concat([od2,uod[col_add]],axis=1)

,Scrip Symbol,Company Name,Quantity,Avg Buy Price,Buy Value,Avg Sell Price,Sell Value,Gross PnL,Brokerage,Add Charges,...,RR,TAR RR,Post Funds,Pre Funds,Post Funds,DATE,RSI,VOLUME,RR,TAR RR
0,TATAMOTORS,TATA MOTORS LIMITED,18.0,1045.80,18824.40,1057.55,19035.90,211.50,11.36,2.2701.220.041500,...,2,2.00,4190.00,4000.00,4190.00,August 5,30,1.4M u - 450k,2,2.00
1,TATAMOTORS,TATA MOTORS LIMITED,20.0,1026.75,20535.00,1020.46,20409.10,-125.90,12.28,2.4601.320.041500,...,NaN,NaN,4042.00,4190.00,4042.00,August 7,NaN,NO DATA AVAILABLE,NaN,NaN
2,TATAMOTORS,TATA MOTORS LIMITED,19.0,1049.25,19935.75,1040.35,19766.65,-169.10,11.91,2.3801.280.041500,...,NaN,NaN,3851.00,4042.00,3851.00,August 8,NaN,NaN,NaN,NaN
3,TATAMOTORS,TATA MOTORS LIMITED,17.0,1079.00,18343.00,1073.80,18254.60,-88.40,10.98,2.1901.180.041500,...,NaN,NaN,3742.21,3851.00,3742.21,August 12,NaN,NaN,NaN,NaN
4,TATAMOTORS,TATA MOTORS LIMITED,34.0,1059.88,36035.75,1063.29,36152.00,116.25,21.66,4.3302.320.071900,...,NaN,NaN,3819.65,3742.21,3819.65,August 13,NaN,NaN,NaN,NaN
5,TATAMOTORS,TATA MOTORS LIMITED,17.0,1050.00,17849.95,1058.30,17991.10,141.15,10.75,2.1501.150.041400,...,NaN,NaN,3919.50,3819.65,3919.50,August 14,NaN,NaN,NaN,NaN
6,TATAMOTORS,TATA MOTORS LIMITED,17.0,1098.50,18674.50,1086.70,18473.90,-200.60,11.14,2.2301.20.041500,...,NaN,NaN,NaN,NaN,NaN,August 16,NaN,NaN,NaN,NaN
7,TATAMOTORS,TATA MOTORS LIMITED,16.0,1091.55,17464.80,1092.25,17476.00,11.20,10.48,2.101.130.041400,...,NaN,NaN,NaN,NaN,NaN,August 19,NaN,NaN,NaN,NaN
8,TATAMOTORS,TATA MOTORS LIMITED,16.0,1086.65,17386.40,1088.95,17423.20,36.80,10.44,2.0901.120.031400,...,NaN,NaN,NaN,3708.00,NaN,August 20,NaN,NaN,NaN,NaN
9,TATAMOTORS,TATA MOTORS LIMITED,16.0,1086.05,17376.80,1085.30,17364.80,-12.00,10.42,2.0801.120.031400,...,NaN,NaN,3690.00,3690.00,3690.00,August 21,NaN,NaN,NaN,NaN
10,TATAMOTORS,TATA MOTORS LIMITED,16.0,1082.45,17319.20,1077.95,17247.20,-72.00,10.37,2.0701.110.031400,...,NaN,NaN,3566.00,3690.00,3566.00,August 22,NaN,NaN,NaN,NaN
11,OFSS,ORACLE FIN SERV SOFT LTD.,6.0,11352.74,68116.45,11288.68,67732.05,-384.40,40.75,8.1504.370.1421700,...,Loss,1.88,8387.00,8587.61,8387.00,11 Sep,65,33k,Loss,1.88
12,OFSS,ORACLE FIN SERV SOFT LTD.,3.0,11714.00,35142.00,11685.65,35056.95,-85.05,21.06,4.2102.260.071900,...,Loss,2.00,NaN,8287.00,NaN,11 Sep,54,247,Loss,2.00
13,OLAELEC,OLA ELECTRIC MOBILITY LTD,1.0,101.30,101.30,101.26,101.26,-0.04,0.06,0.0100.0100000,...,Loss,2.00,8123.00,8123.00,8123.00,12 Sep,60,17k,Loss,2.00
14,TCS,TATA CONSULTANCY SERV LT,20.0,4266.85,85337.05,4285.87,85717.30,380.25,51.32,10.2105.080.1732100.17,...,2,2.00,18573.00,18284.00,18573.00,October 10,60ish,11.8k (Pump),2,2.00
15,ADANIENT,ADANI ENTERPRISES LIMITED,6.0,3130.80,18784.80,3171.25,19027.50,242.70,11.34,2.2601.120.041500.04,...,2,2.00,18743.00,18573.00,18743.00,October 11,61,13k,2,2.00
16,LT,LARSEN & TOUBRO LTD.,14.0,3540.00,49560.00,3555.10,49771.40,211.40,29.80,5.9302.950.111200.1,...,1,2.00,18954.00,18743.00,18954.00,October 14,60ish,7k,1,2.00
17,APOLLO,APOLLO MICRO SYSTEMS LTD,500.0,101.11,50555.00,100.83,50415.29,-139.71,30.29,6.03030.11.5212.6200.1,...,NaN,NaN,NaN,18953.00,NaN,October 15,NaN,NaN,NaN,NaN
18,SOUTHBANK,THE SOUTH INDIAN BANK LTD,2100.0,23.97,50337.00,24.02,50442.00,105.00,30.23,6.0202.990.11.4812.3800.1,...,NaN,NaN,18843.00,NaN,18843.00,October 15,NaN,"Typical Data, why lost AMS is bad SL placement...",NaN,NaN
19,MAZDOCK,MAZAGON DOCK SHIPBUIL LTD,3.0,4340.90,13022.70,4336.62,13009.85,-12.85,7.81,1.5500.770.030300.03,...,NaN,NaN,NaN,NaN,NaN,October16,NaN,NaN,NaN,NaN
20,INFY,INFOSYS LIMITED,20.0,1963.45,39269.00,1974.02,39480.35,211.35,23.62,4.702.340.0811000.08,...,1.2,2.00,18956.00,18843.00,18956.00,October 17,70,118k,1.2,2.00
21,LT,LARSEN & TOUBRO LTD.,10.0,3578.85,35788.50,3584.45,35844.50,56.00,21.49,4.2802.130.071900.07,...,0.45,1.50,18974.00,18956.00,18974.00,October 18,57,48k,0.45,1.50
22,HDFCLIFE,HDFC LIFE INS CO LTD,65.0,743.05,48298.25,746.15,48499.55,201.30,29.04,5.7802.870.11.4512.100.1,...,1.44,1.44,NaN,18974.00,NaN,October 22,47 down,50k,1.44,1.44
23,TATAMOTORS,TATA MOTORS LIMITED,55.0,896.50,49307.50,891.40,49027.00,-280.50,29.50,5.9903.690.11.5712.7200,...,NaN,NaN,18826.00,NaN,18826.00,October 22,NaN,NaN,NaN,NaN
24,RELIANCE,RELIANCE INDUSTRIES LTD,12.0,2721.96,32663.55,2727.90,32734.80,71.25,19.62,3.901.940.070.988.1700.07,...,NaN,NaN,NaN,NaN,NaN,October 22,NaN,NaN,NaN,NaN
25,TECHM,TECH MAHINDRA LIMITED,25.0,1732.60,43314.95,1709.03,42725.85,-589.10,25.81,5.1402.560.0911100.09,...,-L,1.05,18197.00,18826.00,18197.00,October 23,54k,63,-L,1.05
26,WIPRO,WIPRO LTD,80.0,572.50,45800.00,571.05,45684.00,-116.00,27.45,5.4602.720.0911100.09,...,NaN,NaN,18000.00,18197.00,18000.00,October 30,NaN,NO Data,NaN,NaN
27,TATASTEEL,TATA STEEL LIMITED,200.0,155.78,31156.00,155.12,31024.00,-132.00,18.65,3.7101.850.061800.06,...,NaN,NaN,8578.00,8743.00,8578.00,7 November,NaN,Didnt even bothered to record,NaN,NaN
28,TATAMOTORS,TATA MOTORS LIMITED,2.0,809.83,1619.65,810.38,1620.75,1.10,0.97,0.200.1200.050.400,...,NaN,NaN,NaN,NaN,NaN,7 November,NaN,NaN,NaN,NaN
29,ABFRL,ADITYA BIRLA FASHION & RT,100.0,306.60,30660.00,301.10,30110.00,-550.00,18.23,3.6301.80.060.957.600.06,...,NaN,NaN,7996.00,8578.00,7996.00,8 Nov,NaN,NaN,NaN,NaN
30,NTPC,NTPC LTD,65.0,386.60,25129.00,385.10,25031.50,-97.50,15.05,2.9901.490.051600.05,...,NaN,NaN,7899.00,7970.00,7899.00,13 November,NaN,NaN,NaN,NaN
31,TATAMOTORS,TATA MOTORS LIMITED,30.0,774.50,23235.00,768.85,23065.50,-169.50,13.89,2.7601.380.051600.05,...,NaN,NaN,7755.00,7899.00,7755.00,18 Nov,NaN,NaN,NaN,NaN
32,LT,LARSEN & TOUBRO LTD.,7.0,3651.45,25560.15,3651.41,25559.85,-0.30,15.34,3.0501.520.051600.05,...,2,2.00,7627.00,7628.00,7627.00,6 Jan,43,40k,2,2.00
33,TITAN,TITAN COMPANY LIMITED,7.0,3525.45,24678.15,3562.80,24939.60,261.45,14.89,2.9601.470.051600.05,...,1.13,2.00,7763.58,7529.00,7763.58,7 Jan,76,136k-81k,1.13,2.00
34,TRENT,TRENT LTD,2.0,6600.20,13200.40,6714.40,13428.80,228.40,7.99,1.5900.790.030300.03,...,3.5,2.60,7979.90,7763.58,7979.90,8 Jan,8,88k-52k,3.5,2.60
35,M&M,MAHINDRA & MAHINDRA LTD,9.0,3133.96,28205.65,3122.10,28098.90,-106.75,16.89,3.3601.670.061700.06,...,L,1.90,7843.11,7979.90,7843.11,9 Jan,73,60k-24k,L,1.90
36,IREDA,INDIAN RENEWABLE ENERGY,60.0,215.40,12924.00,212.11,12726.53,-197.47,7.70,1.5300.760.030300.03,...,L,2.00,7632.60,7843.11,7632.60,10 Jan,28,4M-1.7M,L,2.00
37,TCS,TATA CONSULTANCY SERV LT,6.0,4301.50,25809.00,4273.55,25641.30,-167.70,15.44,3.0701.530.051600.05,...,L,2.00,7492.04,7632.60,7492.04,13 Jan,NaN,NO,L,2.00
38,RELIANCE,RELIANCE INDUSTRIES LTD,20.0,1243.65,24873.00,1239.10,24782.00,-91.00,14.90,2.9601.470.051600.05,...,L,2.00,7427.48,7492.04,7427.48,14 Jan,NaN,NaN,L,2.00
39,LT,LARSEN & TOUBRO LTD.,20.0,3590.63,71812.50,3587.98,71759.50,-53.00,43.07,8.5704.260.1421800.14,...,Lx2,3.00,7298.28,7427.48,7298.28,20 Jan,77,39K ↑ - 26k,Lx2,3.00
40,Total,NaN,NaN,NaN,1224006.10,NaN,1222652.33,-1353.77,733.99,146.35075.062.4741302.9901.72,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [292]:
MOD2=od2.to_csv("/Users/surisettivamsikrishna/Downloads/Vamsi Pc/CODES/Mark 3/Cleaned_Data/MOD3.csv")

In [ ]:
od2=pd.read_csv("/Users/surisettivamsikrishna/Downloads/Vamsi Pc/CODES/Mark 3/Cleaned_Data/MOD3.csv")