In [2]:
import pandas as pd
rough = pd.read_csv('/Users/surisettivamsikrishna/Downloads/Vamsi Pc/CODES/Mark 3/Raw_Data/official_data.csv')
rough.head(5)

,Date Range,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,From Date,31/07/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,To Date,20/01/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Equity P&L Summary,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Total Gross PnL,-1353.77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
rough.columns

Index(['Date Range', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19'],
      dtype='object')

1: is leaving the first, like expect the first one !
:-1 is leaving the last, like expect the last one !
:1 is like only the first one !
-1: is like only the last one !
[:,1] is like saying first column items
[1,:] is ike saying first column items only

In [43]:
rough.iloc[:,:1]

            Date Range
0            From Date
1              To Date
2                  NaN
3   Equity P&L Summary
4      Total Gross PnL
..                 ...
62          TATAMOTORS
63          TATAMOTORS
64          TATAMOTORS
65          TATAMOTORS
66               Total

[67 rows x 1 columns]

In [47]:
sample = pd.read_csv("/Users/surisettivamsikrishna/Downloads/Vamsi Pc/CODES/Mark 3/Raw_Data/MOD1.csv")
sample.head(5)

,Scrip Symbol,Company Name,Quantity,Avg Buy Price,Buy Value,Avg Sell Price,Sell Value,Gross PnL,Brokerage,Add Charges,Intraday PnL,Opted
0,RELIANCE,RELIANCE INDUSTRIES LTD,20.0,1243.65,24873.00,1239.10,24782.00,-91.00,14.90,2.9601.470.051600.05,-117.44,SELL
1,TCS,TATA CONSULTANCY SERV LT,6.0,4301.50,25809.00,4273.55,25641.30,-167.70,15.44,3.0701.530.051600.05,-194.84,SELL
2,IREDA,INDIAN RENEWABLE ENERGY,60.0,215.40,12924.00,212.11,12726.53,-197.47,7.70,1.5300.760.030300.03,-210.51,SELL
3,M&M,MAHINDRA & MAHINDRA LTD,9.0,3133.96,28205.65,3122.10,28098.90,-106.75,16.89,3.3601.670.061700.06,-136.79,SELL
4,TRENT,TRENT LTD,2.0,6600.20,13200.40,6714.40,13428.80,228.40,7.99,1.5900.790.030300.03,214.98,BUYYY

In [55]:
# Define the data correctly as a dictionary
mini = {
    "Index": [0, 1, 2, 3, 4],  
    "Symbol": ["AAPL", "TSLA", "AMZN", "GOOGL", "MSFT"],  
    "Price": [175, 750, 3200, 2800, 299],  
    "Volume": [10000, 12000, 9000, 8000, 15000],  
    "Change": [+2.3, -5.1, +1.2, -0.9, +3.0]  
}

mini = pd.DataFrame(mini)
print(mini)

   Index Symbol  Price  Volume  Change
0      0   AAPL    175   10000     2.3
1      1   TSLA    750   12000    -5.1
2      2   AMZN   3200    9000     1.2
3      3  GOOGL   2800    8000    -0.9
4      4   MSFT    299   15000     3.0

In [103]:
mini.iloc[:]

   Index Symbol  Price  Volume  Change
0      0   AAPL    175   10000     2.3
1      1   TSLA    750   12000    -5.1
2      2   AMZN   3200    9000     1.2
3      3  GOOGL   2800    8000    -0.9
4      4   MSFT    299   15000     3.0

In [104]:
mini.iloc[::-1]

   Index Symbol  Price  Volume  Change
4      4   MSFT    299   15000     3.0
3      3  GOOGL   2800    8000    -0.9
2      2   AMZN   3200    9000     1.2
1      1   TSLA    750   12000    -5.1
0      0   AAPL    175   10000     2.3

In [95]:
mini.iloc[-1:4,:]

Empty DataFrame
Columns: [Index, Symbol, Price, Volume, Change]
Index: []

In [ ]:
1: is leaving the first, like expect the first one !
:-1 is leaving the last, like expect the last one !
:1 is like only the first one !
-1: is like only the last one !
[:,1] is like saying first column items
[1,:] is ike saying first column items only