## Understanding Universal Stats

Explicitly when I trade, consisder these Factors to be important.
Finding Co-relations between them and adding conditional probability, with matching a strategy would help me get a good strategy!

Aiming for atleast 70% accuracy !!

In [16]:
import pandas as pd
FDI = pd.read_csv("/Users/surisettivamsikrishna/Downloads/Vamsi Pc/CODES/Mark 3/UNIV DATA/FII:DII.csv")

FDI.head(5)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,FII,NaN,NaN,DII,NaN,NaN
3,NaN,Date,Gross Purchase,Gross Sales,Net Purchase / Sales,Gross Purchase,Gross Sales,Net Purchase / Sales
4,NaN,Total,259256.89,318244.97,-58988.08,277187,212333.81,64853.19

In [17]:
FDI= FDI.iloc[3:,1:]
FDI.head(5)

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
3,Date,Gross Purchase,Gross Sales,Net Purchase / Sales,Gross Purchase,Gross Sales,Net Purchase / Sales
4,Total,259256.89,318244.97,-58988.08,277187,212333.81,64853.19
5,28-Feb-2025,"39,239.44","50,878.46","-11,639.02","28,065.55","15,756.92","12,308.63"
6,27-Feb-2025,"19,055.23","19,611.79",-556.56,"13,530.17","11,803.06","1,727.11"
7,25-Feb-2025,"12,500.37","16,029.47","-3,529.10","11,278.09","8,247.31","3,030.78"

In [18]:
FDI.reset_index(drop=True)
FDI.columns=FDI.iloc[0]
FDI=FDI.iloc[1:].reset_index(drop=True)

In [21]:
FDI=FDI.iloc[1:]
FDI.head(5)

3,Date,Gross Purchase,Gross Sales,Net Purchase / Sales,Gross Purchase,Gross Sales,Net Purchase / Sales
1,28-Feb-2025,"39,239.44","50,878.46","-11,639.02","28,065.55","15,756.92","12,308.63"
2,27-Feb-2025,"19,055.23","19,611.79",-556.56,"13,530.17","11,803.06","1,727.11"
3,25-Feb-2025,"12,500.37","16,029.47","-3,529.10","11,278.09","8,247.31","3,030.78"
4,24-Feb-2025,"7,905.53","14,192.23","-6,286.70","12,552.14","7,366.49","5,185.65"
5,21-Feb-2025,"10,144.33","13,593.48","-3,449.15","12,889.44","10,004.83","2,884.61"

In [23]:
FDI.columns = ['Date', 'Gross Purchase FII', 'Gross Sales FII', 'Net Purchase FII',
               'Gross Purchase DII', 'Gross Sales DII', 'Net Purchase DII']
FDI.head(5)

,Date,Gross Purchase FII,Gross Sales FII,Net Purchase FII,Gross Purchase DII,Gross Sales DII,Net Purchase DII
1,28-Feb-2025,"39,239.44","50,878.46","-11,639.02","28,065.55","15,756.92","12,308.63"
2,27-Feb-2025,"19,055.23","19,611.79",-556.56,"13,530.17","11,803.06","1,727.11"
3,25-Feb-2025,"12,500.37","16,029.47","-3,529.10","11,278.09","8,247.31","3,030.78"
4,24-Feb-2025,"7,905.53","14,192.23","-6,286.70","12,552.14","7,366.49","5,185.65"
5,21-Feb-2025,"10,144.33","13,593.48","-3,449.15","12,889.44","10,004.83","2,884.61"

In [24]:
FDI.to_csv("/Users/surisettivamsikrishna/Downloads/Vamsi Pc/CODES/Mark 3/Cleaned_Data_UD/FDI.csv")

In [46]:
GOLD=pd.read_csv("/Users/surisettivamsikrishna/Downloads/Vamsi Pc/CODES/Mark 3/UNIV DATA/GOLD - Sheet1.csv")
GOLD.head(5)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Date,Price,Open,High,Low,Vol.,Change %
2,NaN,"Mar 03, 2025","2,882.61","2,882.06","2,888.59","2,868.90",82.35K,0.00%
3,NaN,"Mar 02, 2025","2,882.47","2,867.85","2,888.15","2,867.40",0.01K,0.0119
4,NaN,"Feb 28, 2025","2,848.50","2,889.00","2,896.10","2,844.10",210.56K,-1.64%

In [48]:
GOLD1=GOLD.iloc[1:,1:]
GOLD1.head(5)

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
1,Date,Price,Open,High,Low,Vol.,Change %
2,"Mar 03, 2025","2,882.61","2,882.06","2,888.59","2,868.90",82.35K,0.00%
3,"Mar 02, 2025","2,882.47","2,867.85","2,888.15","2,867.40",0.01K,0.0119
4,"Feb 28, 2025","2,848.50","2,889.00","2,896.10","2,844.10",210.56K,-1.64%
5,"Feb 27, 2025","2,895.90","2,931.40","2,935.80","2,879.00",207.65K,-0.75%

In [58]:
GOLD1.columns=GOLD1.iloc[0]
GOLD1.reset_index(drop=True)
GOLD1.head(5)

1          Date     Price      Open      High       Low     Vol.  Change %
1          Date     Price      Open      High       Low     Vol.  Change %
2  Mar 03, 2025  2,882.61  2,882.06  2,888.59  2,868.90   82.35K     0.00%
3  Mar 02, 2025  2,882.47  2,867.85  2,888.15  2,867.40    0.01K    0.0119
4  Feb 28, 2025  2,848.50  2,889.00  2,896.10  2,844.10  210.56K    -1.64%
5  Feb 27, 2025  2,895.90  2,931.40  2,935.80  2,879.00  207.65K    -0.75%

In [72]:
GOLD2=GOLD1.iloc[1:]
GOLD2.head(5)

1          Date     Price      Open      High       Low     Vol. Change %
2  Mar 03, 2025  2,882.61  2,882.06  2,888.59  2,868.90   82.35K    0.00%
3  Mar 02, 2025  2,882.47  2,867.85  2,888.15  2,867.40    0.01K   0.0119
4  Feb 28, 2025  2,848.50  2,889.00  2,896.10  2,844.10  210.56K   -1.64%
5  Feb 27, 2025  2,895.90  2,931.40  2,935.80  2,879.00  207.65K   -0.75%
6  Feb 26, 2025  2,917.80  2,915.60  2,926.40  2,891.00    2.05K   0.0041

In [82]:
GOLD2['Yesterday Price']=GOLD2['Price'].shift(-1)
GOLD2.head(5)

/var/folders/10/4p6gdwfx3g74kjfj2_xqxz140000gn/T/ipykernel_1209/2623556838.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GOLD2['Yesterday Price']=GOLD2['Price'].shift(-1)

1,Date,Price,Open,High,Low,Vol.,Change %,Yesterday Price
2,"Mar 03, 2025","2,882.61","2,882.06","2,888.59","2,868.90",82.35K,0.00%,"2,882.47"
3,"Mar 02, 2025","2,882.47","2,867.85","2,888.15","2,867.40",0.01K,0.0119,"2,848.50"
4,"Feb 28, 2025","2,848.50","2,889.00","2,896.10","2,844.10",210.56K,-1.64%,"2,895.90"
5,"Feb 27, 2025","2,895.90","2,931.40","2,935.80","2,879.00",207.65K,-0.75%,"2,917.80"
6,"Feb 26, 2025","2,917.80","2,915.60","2,926.40","2,891.00",2.05K,0.0041,"2,906.00"

In [83]:
GOLD3=GOLD2.iloc[1:]
GOLD3.head(5)

1,Date,Price,Open,High,Low,Vol.,Change %,Yesterday Price
3,"Mar 02, 2025","2,882.47","2,867.85","2,888.15","2,867.40",0.01K,0.0119,"2,848.50"
4,"Feb 28, 2025","2,848.50","2,889.00","2,896.10","2,844.10",210.56K,-1.64%,"2,895.90"
5,"Feb 27, 2025","2,895.90","2,931.40","2,935.80","2,879.00",207.65K,-0.75%,"2,917.80"
6,"Feb 26, 2025","2,917.80","2,915.60","2,926.40","2,891.00",2.05K,0.0041,"2,906.00"
7,"Feb 25, 2025","2,906.00","2,955.90","2,955.90","2,884.50",5.59K,-1.48%,"2,949.70"

In [84]:
GOLD3.dtypes

1
Date               object
Price              object
Open               object
High               object
Low                object
Vol.               object
Change %           object
Yesterday Price    object
dtype: object

In [85]:
GOLD3['Price'] = GOLD3['Price'].str.replace(',', '', regex=True).astype(float)
GOLD3['Yesterday Price'] = GOLD3['Yesterday Price'].str.replace(',', '', regex=True).astype(float)

GOLD3['Change Pts'] = GOLD3['Price'] - GOLD3['Yesterday Price']

/var/folders/10/4p6gdwfx3g74kjfj2_xqxz140000gn/T/ipykernel_1209/3198500820.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GOLD3['Price'] = GOLD3['Price'].str.replace(',', '', regex=True).astype(float)
/var/folders/10/4p6gdwfx3g74kjfj2_xqxz140000gn/T/ipykernel_1209/3198500820.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GOLD3['Yesterday Price'] = GOLD3['Yesterday Price'].str.replace(',', '', regex=True).astype(float)
/var/folders/10/4p6gdwfx3g74kjfj2_xqxz140000gn/T/ipykernel_1209/3198500820.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GOLD3['Change Pts'] = GOLD3['Price'] - GOLD3['Yesterday Price']

In [86]:
GOLD3['Change Pts']=GOLD3['Price']-GOLD3['Yesterday Price']
GOLD3.head(5)

/var/folders/10/4p6gdwfx3g74kjfj2_xqxz140000gn/T/ipykernel_1209/2937414243.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GOLD3['Change Pts']=GOLD3['Price']-GOLD3['Yesterday Price']

1,Date,Price,Open,High,Low,Vol.,Change %,Yesterday Price,Change Pts
3,"Mar 02, 2025",2882.47,"2,867.85","2,888.15","2,867.40",0.01K,0.0119,2848.5,33.97
4,"Feb 28, 2025",2848.50,"2,889.00","2,896.10","2,844.10",210.56K,-1.64%,2895.9,-47.40
5,"Feb 27, 2025",2895.90,"2,931.40","2,935.80","2,879.00",207.65K,-0.75%,2917.8,-21.90
6,"Feb 26, 2025",2917.80,"2,915.60","2,926.40","2,891.00",2.05K,0.0041,2906.0,11.80
7,"Feb 25, 2025",2906.00,"2,955.90","2,955.90","2,884.50",5.59K,-1.48%,2949.7,-43.70

In [92]:
GOLD3['Change Pts'].iloc[-1:]

107   NaN
Name: Change Pts, dtype: float64

In [93]:
GOLD4=GOLD3.iloc[:-1]
GOLD4.head(5)

1,Date,Price,Open,High,Low,Vol.,Change %,Yesterday Price,Change Pts
3,"Mar 02, 2025",2882.47,"2,867.85","2,888.15","2,867.40",0.01K,0.0119,2848.5,33.97
4,"Feb 28, 2025",2848.50,"2,889.00","2,896.10","2,844.10",210.56K,-1.64%,2895.9,-47.40
5,"Feb 27, 2025",2895.90,"2,931.40","2,935.80","2,879.00",207.65K,-0.75%,2917.8,-21.90
6,"Feb 26, 2025",2917.80,"2,915.60","2,926.40","2,891.00",2.05K,0.0041,2906.0,11.80
7,"Feb 25, 2025",2906.00,"2,955.90","2,955.90","2,884.50",5.59K,-1.48%,2949.7,-43.70

In [95]:
GOLD4.shape

(104, 9)

In [96]:
GOLD4.to_csv("/Users/surisettivamsikrishna/Downloads/Vamsi Pc/CODES/Mark 3/Cleaned_Data_UD/GOLD.csv")

In [97]:
nifty = pd.read_csv("/Users/surisettivamsikrishna/Downloads/Vamsi Pc/CODES/Mark 3/UNIV DATA/NIFTY 50.csv")
nifty.head(5)

  Index Name         Date      Open      High       Low     Close
0   NIFTY 50  03 Mar 2025  22194.55  22261.55  22004.70  22119.30
1   NIFTY 50  28 Feb 2025  22433.40  22450.35  22104.85  22124.70
2   NIFTY 50  27 Feb 2025  22568.95  22613.30  22508.40  22545.05
3   NIFTY 50  25 Feb 2025  22516.45  22625.30  22513.90  22547.55
4   NIFTY 50  24 Feb 2025  22609.35  22668.05  22518.80  22553.35

In [ ]:
nifty['Previous day']= nifty['Close'].shift(-1)
nifty.head(5)

,Index Name,Date,Open,High,Low,Close,Previous day
0,NIFTY 50,03 Mar 2025,22194.55,22261.55,22004.70,22119.30,22124.70
1,NIFTY 50,28 Feb 2025,22433.40,22450.35,22104.85,22124.70,22545.05
2,NIFTY 50,27 Feb 2025,22568.95,22613.30,22508.40,22545.05,22547.55
3,NIFTY 50,25 Feb 2025,22516.45,22625.30,22513.90,22547.55,22553.35
4,NIFTY 50,24 Feb 2025,22609.35,22668.05,22518.80,22553.35,22795.90

In [101]:
nifty.drop(columns=['High','Low'],inplace=True)
nifty.iloc[:-1]
nifty.head(5)

  Index Name         Date      Open     Close  Previous day
0   NIFTY 50  03 Mar 2025  22194.55  22119.30      22124.70
1   NIFTY 50  28 Feb 2025  22433.40  22124.70      22545.05
2   NIFTY 50  27 Feb 2025  22568.95  22545.05      22547.55
3   NIFTY 50  25 Feb 2025  22516.45  22547.55      22553.35
4   NIFTY 50  24 Feb 2025  22609.35  22553.35      22795.90

In [102]:
nifty.dtypes

Index Name       object
Date             object
Open            float64
Close           float64
Previous day    float64
dtype: object

In [103]:
nifty['Change pts']=nifty['Close']-nifty['Previous day']

In [104]:
nifty.head(5)

  Index Name         Date      Open     Close  Previous day  Change pts
0   NIFTY 50  03 Mar 2025  22194.55  22119.30      22124.70       -5.40
1   NIFTY 50  28 Feb 2025  22433.40  22124.70      22545.05     -420.35
2   NIFTY 50  27 Feb 2025  22568.95  22545.05      22547.55       -2.50
3   NIFTY 50  25 Feb 2025  22516.45  22547.55      22553.35       -5.80
4   NIFTY 50  24 Feb 2025  22609.35  22553.35      22795.90     -242.55

In [105]:
nifty.to_csv("/Users/surisettivamsikrishna/Downloads/Vamsi Pc/CODES/Mark 3/Cleaned_Data_UD/Nifty.csv")

In [106]:
USB =pd.read_csv("/Users/surisettivamsikrishna/Downloads/Vamsi Pc/CODES/Mark 3/UNIV DATA/USBond Yield 10Y.csv")
USB.head(5)

  observation_date  DGS10
0       2024-09-03   3.84
1       2024-09-04   3.77
2       2024-09-05   3.73
3       2024-09-06   3.72
4       2024-09-09   3.70

In [109]:
USB=USB.iloc[::-1]
USB.head(5)

    observation_date  DGS10
127       2025-02-27   4.29
126       2025-02-26   4.25
125       2025-02-25   4.30
124       2025-02-24   4.40
123       2025-02-21   4.42

In [110]:
USB['DGS10'].mean()

4.273471074380166

In [111]:
USB.to_csv('/Users/surisettivamsikrishna/Downloads/Vamsi Pc/CODES/Mark 3/Cleaned_Data_UD/USB.csv')

In [113]:
DINR=pd.read_csv("/Users/surisettivamsikrishna/Downloads/Vamsi Pc/CODES/Mark 3/UNIV DATA/USD_INR.csv")
DINR.head(5)

         Date   Price    Open    High     Low  Vol. Change %
0  03-03-2025  87.270  87.444  87.424  87.253   NaN   -0.22%
1  28-02-2025  87.466  87.320  87.559  87.266   NaN    0.16%
2  27-02-2025  87.330  87.108  87.427  87.106   NaN    0.25%
3  26-02-2025  87.113  87.086  87.192  87.014   NaN   -0.02%
4  25-02-2025  87.130  86.698  87.263  86.674   NaN    0.54%

In [118]:
DINR.drop(columns=['Vol.', 'Open', 'High', 'Low'], inplace=True)
DINR['Previous_day']=DINR['Price'].shift(-1)
DINR['Change Pts']=DINR['Price']-DINR['Previous_day']
DINR.head(5)

         Date   Price Change %  Previous_day  Change Pts
0  03-03-2025  87.270   -0.22%        87.466      -0.196
1  28-02-2025  87.466    0.16%        87.330       0.136
2  27-02-2025  87.330    0.25%        87.113       0.217
3  26-02-2025  87.113   -0.02%        87.130      -0.017
4  25-02-2025  87.130    0.54%        86.660       0.470

In [119]:
DINR.iloc[:-1]
DINR.head(5)

         Date   Price Change %  Previous_day  Change Pts
0  03-03-2025  87.270   -0.22%        87.466      -0.196
1  28-02-2025  87.466    0.16%        87.330       0.136
2  27-02-2025  87.330    0.25%        87.113       0.217
3  26-02-2025  87.113   -0.02%        87.130      -0.017
4  25-02-2025  87.130    0.54%        86.660       0.470

In [122]:
DINR.to_csv("/Users/surisettivamsikrishna/Downloads/Vamsi Pc/CODES/Mark 3/Cleaned_Data_UD/DINR.csv")